### ISSUE TITLE
Support Elasticsearch

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/archiveless#60]
### Description

Make sure this plugin's logic is respected when using one of those plugins: 

- VIP Search
- ElasticSearch
- SearchPress

### Use Case

A site that uses ElasticSearch.

**Comment by mboynes** [comment]
I would suggest that this may not be necessary. The purpose of this plugin is query performance (to avoid NOT IN queries et al); if a query is being replaced with Elasticsearch, then it shouldn't need archiveless.

**Comment by renatonascalves** [comment]
Agree! After a bit more reflection, what we need is actually a `elasticsearch-archiveless` plugin.
